# Generated by Django 4.2.4 on 2023-09-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0002_crop_family_crop_gender_crop_max_temperature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='irrigation_parameters',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='description',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='crop',
            name='soil_components',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
