# Generated by Django 4.2.4 on 2023-09-13 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0003_crop_irrigation_parameters_crop_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='image',
        ),
    ]
